### ISSUE TITLE
Third Party Ringtones Don't Always Play

### ISSUE THREAD

**Issue by billatq** [billatq/beeper#5]
Reported on CM11 and other non-AOSP builds in the past.

**Comment by billatq** [comment]
This might just be an issue of needing permission to read arbitrary files on the system:

```
07-13 23:51:03.756 E/DatabaseUtils(11664): Writing exception to parcel
07-13 23:51:03.756 E/DatabaseUtils(11664): java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media/48509 from pid=16863, uid=10180 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
07-13 23:51:03.756 E/DatabaseUtils(11664):  at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:467)
07-13 23:51:03.756 E/DatabaseUtils(11664):  at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:394)
07-13 23:51:03.756 E/DatabaseUtils(11664):  at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:387)
07-13 23:51:03.756 E/DatabaseUtils(11664):  at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:339)
07-13 23:51:03.756 E/DatabaseUtils(11664):  at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:312)
07-13 23:51:03.756 E/DatabaseUtils(11664):  at android.os.Binder.execTransact(Binder.java:404)
```
